DENIAL_MAPPING = {
    "Bed availability: No female beds": "No Available Bed",
    "Bed availability: No ISO beds (required)": "No Available Bed",
    "Bed availability: No LTC beds": "No Available Bed",
    "Bed availability: No male beds": "No Available Bed",
    "Bed availability: No private beds (requested)": "No Available Bed",
    "Business Office - No SNF benefits": "Benefits Exhausted",
    "Business: Incarceration": "Care Needs Exceed Current Capacity",
    "Business: Megans law positive": "Other (see comments)",
    "Business: No contract with insurance": "Not a Covered Benefit",
    "Business: Out-of-network insurance": "Out of Network",
    "Business: Outstanding AR balance": "Not a Covered Benefit",
    "Hospice is not offered": "Care Needs Exceed Current Capacity",
    "Transport": "Care Needs Exceed Current Capacity",
    "Clinical: Cannot meet clinical needs": "Care Needs Exceed Current Capacity",
    "Clinical: High cost medications/equipment": "Care Needs Exceed Current Capacity",
    "Clinical: Sitter needs": "Care Needs Exceed Current Capacity",
    "Financial": "Not a Covered Benefit",
    "Financial: MA Pending": "Not a Covered Benefit",
    "High risk": "Care Needs Exceed Current Capacity",
    "Services: Alcohol use/abuse": "Care Needs Exceed Current Capacity",
    "Services: Bariatric": "Care Needs Exceed Current Capacity",
    "Services: Behaviors, uncontrolled": "Care Needs Exceed Current Capacity",
    "Services: Drug use & abuse": "Care Needs Exceed Current Capacity",
    "Services: Homeless": "Other (see comments)",
    "Staffing: Lack of 24 hr RN coverage": "No Available Bed",
    "Staffing: Lack of other (non-RN) coverage": "No Available Bed",
}

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

DENIAL_MAPPING = {
    "No female beds": "No Available Bed",
    "No ISO beds (required)": "No Available Bed",
    "No LTC beds": "No Available Bed",
    "No male beds": "No Available Bed",
    "No private beds (requested)": "No Available Bed",
    "No SNF benefits": "Benefits Exhausted",
    "Incarceration": "Care Needs Exceed Current Capacity",
    "Megans law positive": "Other (see comments)",
    "No contract with insurance": "Not a Covered Benefit",
    "Out-of-network insurance": "Out of Network",
    "Outstanding AR balance": "Not a Covered Benefit",
    "Hospice is not offered": "Care Needs Exceed Current Capacity",
    "Transport": "Care Needs Exceed Current Capacity",
    "Cannot meet clinical needs": "Care Needs Exceed Current Capacity",
    "High cost medications/equipment": "Care Needs Exceed Current Capacity",
    "Sitter needs": "Care Needs Exceed Current Capacity",
    "Financial": "Not a Covered Benefit",
    "MA Pending": "Not a Covered Benefit",
    "High risk": "Care Needs Exceed Current Capacity",
    "Alcohol use/abuse": "Care Needs Exceed Current Capacity",
    "Bariatric": "Care Needs Exceed Current Capacity",
    "Behaviors, uncontrolled": "Care Needs Exceed Current Capacity",
    "Drug use & abuse": "Care Needs Exceed Current Capacity",
    "Homeless": "Other (see comments)",
    "Lack of 24 hr RN coverage": "No Available Bed",
    "Staffing: Lack of other (non-RN) coverage": "No Available Bed",
}

Community_Mapping = {
    "Walnut Creek":"Walnut Creek Healthcare and Rehabilitation Center",
    "Meadowcrest":"Meadowcrest Nursing Center",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    
}